### ISSUE TITLE
Define Objective Function

### ISSUE THREAD

**Issue by pszittyay** [afish/MilpManager#1]
Hi,
I am using Milp + LpSolveMilp in replace for Microsoft Solver Foundation due to a varaible restriction. I have elaborated a simple test programa but i have no found how to define the objetive function. I have read the example and the code but i cannot find where to set the type of objetive function (min/max)

```
            var solver = new LpSolveMilpManager.Implementation.LpSolveMilpSolver(5);
            //Variables
            IVariable x1 = solver.Create("x1", Domain.PositiveOrZeroReal);
            IVariable x2 = solver.Create("x2", Domain.PositiveOrZeroReal);
            //Restricciones           
            //10X1 + 10X2 + X3 = 9
            IVariable ec1 = x1.Operation(OperationType.Multiplication, solver.FromConstant(10));
            IVariable ec2 = x1.Operation(OperationType.Multiplication, solver.FromConstant(10));
            IVariable ecuacion1 = ec1.Operation(OperationType.Addition, ec2);

            ecuacion1.Set(ConstraintType.LessOrEqual, solver.FromConstant(9));

            //10X1 + 5X2 = 1
            IVariable ec3 = x2.Operation(OperationType.Multiplication, solver.FromConstant(5));
            IVariable ecuacion2 = ec1.Operation(OperationType.Addition, ec3);
            ecuacion2.Set(ConstraintType.GreaterOrEqual, solver.FromConstant(1));

            //Funcion Objetivo
            //2X1 + X2
            IVariable objetivo = x1.Operation(OperationType.Multiplication, solver.FromConstant(2)).Operation(OperationType.Addition, x2);

            solver.AddGoal("min", objetivo); <--- How do i set it to min????

            solver.Solve();

            double valorX1 = solver.GetValue(x1);
            double valorX2 = solver.GetValue(x2);
            double resultado = solver.GetValue(objetivo);
```

Thanks in advance and i will be happy to contribute to the project. I am a engineer in Argentina and also a c# programming that has a lor of experience using Microsoft Solver, implemented in the oil and gas industry
# 

I have found that the implemetation of the solver always uses a Max Function
This section of code from your LpSolveMilpSolver

  protected override void InternalAddGoal(string name, IVariable operation)
        {
            var goal = GetRowArray();
            goal[VariableId(operation)] = 1
            lpsolve.set_minim(LpSolvePointer); <-- changed to minimize function
            if (!lpsolve.set_obj_fn(LpSolvePointer, goal))
            {
                throw new InvalidOperationException();
            }
        }

**Comment by afish** [comment]
Hi,
Currently only max cost function is supported and there is no option to change it to minimize — as you pointed out, it is hardcoded. You can always negate your cost function and maximize it which will actually work as a min cost function.
Feel free to contribute to project. Let me know if you have any other questions.
Also please be advised, that LpSolve might give you incorrect results with complex operations (e.g., GCD) since it uses poor arithmetic and has problems with rounding errors. You might consider using OrTools implementation in that case.
Thanks,
Afish

**Comment by pszittyay** [comment]
Thanks for the answer. I woukd like to contribute to the project. I have
been reading the code and i am thinking on how to achieve operator override
to make the code more redable
I will make a pull request when ready
